#!/usr/bin/env python3
"""Regenerate README.md from README_NOTES.md + config + query_params.

Convention:
    README.md = [README_NOTES.md verbatim]
              + "<!-- BEGIN GENERATED -->"
              + auto-generated body (config table, query summary, links)
              + "<!-- END GENERATED -->"

The generated body is byte-stable on identical inputs, so
update-readme.yml only commits when the user edited README_NOTES.md or
changed config/query inputs.

Template-agnostic: pulls the template repo URL from $GITHUB_REPOSITORY
or `git remote get-url origin` rather than hard-coding it, so this
script works unmodified after the template is forked.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

BEGIN = "<!-- BEGIN GENERATED -->"
END   = "<!-- END GENERATED -->"


def _detect_repo() -> str:
    if env := os.environ.get("GITHUB_REPOSITORY"):
        return f"https://github.com/{env}"
    try:
        url = subprocess.check_output(
            ["git", "remote", "get-url", "origin"], text=True
        ).strip()
        if url.endswith(".git"):
            url = url[:-4]
        if url.startswith("git@github.com:"):
            url = "https://github.com/" + url.split(":", 1)[1]
        return url
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def _flatten(d: dict, prefix: str = "") -> list[tuple[str, Any]]:
    """Flatten a nested dict to dotted-key rows for the markdown table."""
    out: list[tuple[str, Any]] = []
    for k, v in d.items():
        key = f"{prefix}{k}" if not prefix else f"{prefix}.{k}"
        if isinstance(v, dict):
            out.extend(_flatten(v, key))
        else:
            out.append((key, v))
    return out


def _format_val(v: Any) -> str:
    if isinstance(v, list):
        return ", ".join(map(str, v))
    return str(v)


def _config_table(cfg: dict) -> str:
    rows = _flatten(cfg)
    if not rows:
        return "_(no config keys found — see `config/user_config.yml`)_"
    lines = ["| Key | Value |", "| --- | --- |"]
    for k, v in rows:
        lines.append(f"| `{k}` | {_format_val(v)} |")
    return "\n".join(lines)


def _query_summary(qp: dict) -> str:
    mode = qp.get("mode", "?")
    lines = [f"**Mode:** `{mode}`"]
    if mode == "archived":
        c = qp.get("compilation", "?"); v = qp.get("version", "?")
        lines.append(f"**Compilation:** `{c}` (version `{v}`)")
        lines.append(f"**Source:** https://lipdverse.org/{c}/{v}/{c}{v}.pkl")
    elif mode == "filtered":
        lines.append("**Filters:**")
        for k, val in (qp.get("filters") or {}).items():
            lines.append(f"- `{k}`: {_format_val(val)}")
    return "\n\n".join(lines)


def build_body(cfg_path: Path, qp_path: Path,
               pages_url: str, releases_url: str, repo_url: str) -> str:
    cfg = yaml.safe_load(cfg_path.read_text()) or {}
    qp  = json.loads(qp_path.read_text())
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""{BEGIN}

> _This section is auto-regenerated by `.github/workflows/update-readme.yml` after
> every successful reconstruction. Hand-edit `README_NOTES.md` (above) for prose
> that should survive regenerations. Last regenerated: {now}_

## Reconstruction inputs

### Data query (`query_params.json`)

{_query_summary(qp)}

### Parameters (`config/user_config.yml`)

{_config_table(cfg)}

## Outputs

- **Visualization:** {pages_url if pages_url else "_(Pages not yet deployed — push to trigger)_"}
- **Releases:** {releases_url}
- **Template source:** {repo_url}

## Workflows

| File | Purpose |
|------|---------|
| `.github/workflows/reconstruct.yml`  | Acquires LiPD data + runs the reconstruction container, commits outputs to `results/`. |
| `.github/workflows/visualize.yml`    | Autodetects spatial vs. 1D output; routes to `presto-viz` or the static-Pages tile UI. |
| `.github/workflows/release-recon.yml`| Bundles each successful run into a `recon-<run_id>` GitHub Release (Zenodo-friendly). |
| `.github/workflows/update-readme.yml`| (this) Regenerates `README.md` after each successful reconstruction. |

See [`ADAPTING.md`](ADAPTING.md) for how to customize this template.

{END}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--notes",        default="README_NOTES.md",        type=Path)
    ap.add_argument("--readme",       default="README.md",              type=Path)
    ap.add_argument("--config",       default="config/user_config.yml", type=Path)
    ap.add_argument("--query-params", default="query_params.json",      type=Path)
    ap.add_argument("--pages-url",    default="")
    ap.add_argument("--releases-url", default="")
    ap.add_argument("--repo-url",     default="")
    args = ap.parse_args()

    repo_url = args.repo_url or _detect_repo()
    notes = args.notes.read_text() if args.notes.exists() else ""

    # If the existing README contains a generated block, splice over it
    # so the prepended notes section is preserved verbatim.
    body = build_body(args.config, args.query_params,
                      args.pages_url, args.releases_url, repo_url)

    if args.readme.exists():
        old = args.readme.read_text()
        if BEGIN in old and END in old:
            head = old.split(BEGIN, 1)[0].rstrip() + "\n\n"
            new = head + body + "\n"
        else:
            # First run — prepend notes (if present), then body.
            new = (notes.rstrip() + "\n\n" if notes else "") + body + "\n"
    else:
        new = (notes.rstrip() + "\n\n" if notes else "") + body + "\n"

    args.readme.write_text(new)
    print(f"[generate_readme] wrote {args.readme} ({len(new)} bytes)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
